spring:
  datasource:
    username: foo
    password: Password123.
    url: jdbc:postgresql://localhost:5432/ffk
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # a day
      refresh-token:
       expiration: 420000 # 7 days